---
- hosts: server

  pre_tasks:
    package:
      update_cache: yes

  handlers:
    - name: restart SSH
      service:
        name: sshd
        state: restarted

  tasks:
    - name: Tell SELinux about SSHs new port
      seport:
        ports: 2849
        proto: tcp
        setype: ssh_port_t
        state: present

    # Ensure to have another SSH session open to prevent lockout from server
    - name: SSH hardeining
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: "sshd -T -f %s"
      with_items:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^Port"
          line: "Port 2849"
      notify: restart SSH

    - name: Set file permissions
        file:- name: Ensure firewalld is running
      service:
        name: firewalld
        state: running
          path: /etc/ssh/sshd_config
          mode: 0600

    - name: Add user
      user:
        name: johndoe

    - name: Add sudo group rights for deployment user
      lineinfile:
        dest: /etc/sudoers
        regexp: "^johndoe"
        line: "johndoe ALL=(ALL) NOPASSWD: ALL"
        state: present
        validate: "visudo -cf %s"

    - name: Remove unused packages
      package:
        name:
          - httpd
          - mailutils
          - python
        state: absent
        purge: yes

    # Difference between firewalld and ufw?
    - name: Install firewalld
      package:
        name: firewalld
        state: present

    - name: Configure ports in firewall
      firewalld:
        state: "{{ item.state }}"
        port: "{{ item.port }}"
        zone: external
        immediate: yes
        permanent: yes
      with_items:
        # for SSH
        - { state: "enabled", port: 2849/tcp }
        # for NTP
        - { state: "enabled", port: 123/udp }

    - name: Ensure firewalld is running
        service:
          name: firewalld
          state: running

    - name: Install fail2ban
      package:
        name: fail2ban
        state: present
