---
- hosts: mariadb
  become: yes
  tasks:
    - name: Ensure NTP is installed
      package:
        name: mariadb
        state: present

    - name: Ensure NTP is running
      service:
        name: ntp
        state: started
        enabled: yes

    - name: Ensure mariadb is running
      package:
       name: mariadb
       state: present

    - name: Ensure mariadb is running
      service:
        name: mariadb
        state: started
        enabled: yes
