---
- hosts: docker-hosts
  become: yes

  pre_tasks:
    - name: Update APT-Cache if needed.
      pacman:
        update_cache: yes
        cache_valid_time: 3600

  tasks:
    - name: Ensure NTP is installed
      package: name=ntp state=present
    - name: Ensure NTP is running
      service: name=ntp state=started enabled=yes

    - name: Ensure docker is installed
      package:
        name: docker
        state: present

    - name: Testdocker
      shell: systemctl enable docker

    - name: Testdocker
      shell: systemctl start docker
