---
- hosts: all
  become: yes

  tasks:
    - name: Install personal programms via pacman
      package:
        name:
          - atom
          - ufw
          - discord
          - filezilla
          - kdeconnect
          - keepassxc
          - obs-studio
          - teamspeak3
          - thunderbird
          - vlc
          - nmap
          - python
          - virtualbox
          - nano
          - p7zip
          - gimp
          - gufw
          - ffmpeg
          - git
          - ansible
        state: latest

    - name: Install personal programms via pamac
      shell: "pamac install linux56-virtualbox-host-modules"
      shell: "pamac install google-chrome"
      shell: "pamac install spotify"
      shell: "pamac install etcher"
      shell: "pamac install skype"
      shell: "pamac install teamviewer"
      shell: "pamac install jetbrains-toolbox"
